### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by kwokkan** [kwokkan/card-hero#3097]
### Current page
https://card-hero.herokuapp.com/Card/1

### Stack trace
```
TypeError: Cannot convert object to primitive value
    at Ei._resolveAnimations (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:42077)
    at Ei.updateElement (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:42564)
    at Ei.update (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:63590)
    at Ei._update (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:39885)
    at en._updateDataset (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:113250)
    at en._updateDatasets (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:113001)
    at en.update (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:112312)
    at new en (https://card-hero.herokuapp.com/dist/vendor.chart.js.882246d8ba584125eade.min.js:2:108178)
    at I (https://card-hero.herokuapp.com/dist/vendor.react-chartjs-2.544c8bf4c4d96a472ca4.min.js:1:2139)
    at https://card-hero.herokuapp.com/dist/vendor.react-chartjs-2.544c8bf4c4d96a472ca4.min.js:1:2823
```

**Comment by kwokkan** [comment]
Fixed in #3099.
